#!/bin/bash

if [ "$*" == "" ]; then
    echo "You choosed no package"
    sleep 3
    exit 1
fi

echo "You choosed to install $1"
read  -n 1 -p "Press enter to continue the installation:" Press any key to proceed
exec /opt/shellpkg-repo/$1/install.sh
clear
echo "Hey, if you are seeing this text, probably the folder don't exist, or it was named wrong. The script will exit"
sleep 3
exit 1

