#!/bin/bash

GENERAL_ERROR=1
USAGE_ERROR=2
PACKAGE_ERROR=3
check_config() {
    sed -ne "/^$1=/s/^$1=//p" /etc/shellpkg.conf
}

if [ -z "$1" ]; then
    echo "No package specified."
    echo "Usage: $(basename $0) <package name>"
    exit $USAGE_ERROR
fi

if [ -f /etc/shellpkg.conf ]; then
    REPO=$(check_config repo)
    # assume the user is not an idiot and don't do proper config validation
else
    echo "Config file not found!"
    exit $GENERAL_ERROR
fi

if [ ! -d $REPO ]; then
    echo "Repo directory not found: $REPO"
    exit $GENERAL_ERROR
fi

if [ -d $REPO/$1 ]; then
    echo "Package: $1"
    echo "============"
    #TODO: dependency and conflict checks
    #echo "============"
    read -n1 -p "Press any key to continue with update or hit ^c to abort."
    #TODO: handle dependencies and conflicts
    #TODO: mark package as starting update
    cd /tmp
    export BASE_DIR=$(check_config base-directory)
    export PACKAGE_DIR=$REPO/$1
    if [ -f $PACKAGE_DIR/status-installed ]
    then
        echo "$Package check OK"
    else
        echo "$1 Package is not installed"
        exit $GENERAL_ERROR
    fi

    if [ $(check_config single-file) = "true" ]; then
        source $PACKAGE_DIR/operations.sh 2>1 &>/dev/null
        if [ $? -ne 0 ]; then
            echo No operations file present.
            read -p "Do you want to use the $(basename $0 | cut -d- -f2) script? " yn
            case ${yn,,} in
                y) $PACKAGE_DIR/update.sh; exit $? ;;
                *) exit $PACKAGE_ERROR ;;
            esac
        fi
        update
    elif [ $(check_config single-file) = "false" ]; then
        $PACKAGE_DIR/update.sh
        exit $?
    fi
    sudo touch $PACKAGE_DIR/status-installed
else
    echo "Unknown package: $1"
    exit $PACKAGE_ERROR
fi
